name: ZodGame-Auto-Checkin

on:
  workflow_dispatch:
  schedule:
    # Actions 任务延迟过高，提前一些时间。
    # UTC+8 ~ 07:33
    - cron: "45 23 * * *"
    - cron: "0 0 * * *"

jobs:
  checkin:
    name: Checkin
    runs-on: ubuntu-latest
    env:
      ACCOUNTS: ${{ secrets.ACCOUNTS }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js latest.
        uses: actions/setup-node@v4
        with:
          node-version: latest

      - name: Checkin
        shell: bash
        run: |
          node main.js
